### PR TITLE
Add postgresql ssl_mode config

### PR DESCRIPTION
**Pull request by Akagi201**
ssl_mode config options: "prefer", "require", no config means none ssl_mode.

### CODE REVIEW

**Review by chirag-bgh — APPROVED** [review]
LGTM

**Comment by zsluedem** [comment]
should we merge into preconf branch? @Akagi201

**Comment by Akagi201** [comment]
@zsluedem the preconf branch commit is a little messed. I will clear it later.

**Comment by zsluedem** [comment]
Just curious. Does this block you? Why are you working on it?

**Comment by Akagi201** [comment]
> Just curious. Does this block you? Why are you working on it?

yes it blocks me with db connection.

**Pull request merged**
