### PR TITLE
Upgrade all deps and fix all warnings

### PR DESCRIPTION
**Pull request by Akagi201**

### CODE REVIEW

**Comment by chirag-bgh** [comment]
@Akagi201 This is very great!

It seems workflows were not enabled previously and I have enabled it now. Can you create a different PR so that it could run the workflow actions?

**Review by zsluedem — CHANGES_REQUESTED** [review]
~~Can you please undo all the formatting codes?~~

~~The problems here with the formatting code is that~~
~~1. It would create a lot of conflicts if we want to merge some additional features from upstream helix and it would possibly create huge amount of work.~~
~~2. In the future, if helix agree to adopt our feature request, they possibly won't accept another format.~~

~~Anyway, I don't see any advantages on another formatting. If you do have a good reason, please let me know. If not, let's stick to original format.~~

nvm. I see you formatting following the rules

**Review by zsluedem — APPROVED** [review]
Execellent work!!

**Comment by zsluedem** [comment]
> @Akagi201 This is very great!
> 
> It seems workflows were not enabled previously and I have enabled it now. Can you create a different PR so that it could run the workflow actions?

I tried the unit locally and a lot of them failed. Created another tasks for this https://www.notion.so/lu-ban/re-enanle-ci-in-helix-repo-10efd86cb60f803c9adcd2f60e84f73a . Closing this one first and move on to next.

**Pull request merged**
